### PR TITLE
Mockup Enhancements

### PR DESCRIPTION
**Pull request by kwilliams1987**
- MockCubeBlock
  - Assigns default value to OwnerId.
  - Assigns default values to all appropriate properties (based on in-game defaults).
  - ToString() now includes DisplayNameText and EntityId for easier tracking.
- MockEntity
  - ~~Assigns an auto-incremental value for EntityId.~~
  - Assigns default values for other appropriate properties (based on in-game defaults).
- MockTerminalBlock
  - Now assigns default values to appropriate properties (based on in-game defaults).
  - ~~Implemented HasPlayerAccess (current player has ID of 1).~~
  - Default implementation of SearchActionsOfName.
  - Default implemention of GetActionWithName.
  - Default implemention of GetProperty.
  - Default implemention of GetProperties.
- MockAirVent implemented.
- MockInteriorLight implemented.
- MockProgrammableBlock
  - Removed some obsolete calls to MDK.Run()
- MockTextPanel
  - Now assigns default values to appropriate properties (based on in-game defaults).
- ~~MockGridSystem added.~~
  - ~~Helper function mock additional game properties such as:~~
    - ~~Next available entity ID.~~
    - ~~Next available grid object ID.~~
    - ~~Player ID.~~
- MockTerminalProperty added.
  - Includes implementations for string, bool, float and Color.
  - Includes standard default values for IMyTerminalBlock.

### CODE REVIEW

**Comment by malware-dev** [comment]
Oh, hello, you've been busy, haven't you 😄 

I'm afraid I have to hold back a little again. For the most part this pull request is fine, but... you _cannot_ use statics like that gridsystem thing in this. These mockups have to function in unit tests. Unit tests does not have a reliable run order, and they can run in parallel. Static storage will also cause problems because it removes predictability. I'm sorry, but it has to go.

Secondly, I see you've implemented some properties and methods that used to have NotImplementedException. The GetProperty stuff seems to be fine, but there are those where you haven't provided an actual replication of their function. These mockups either have to replicate function or not, nothing in between. I mean, the HasLocalAccess methods are probably fine too, but... they actually have no meaning at all in the game, so their use should be discouraged.

**Comment by malware-dev** [comment]
Finally, what do you mean by: `Includes non-standard default values for IMyTerminalBlock.`? We cannot accept non-game replicated behavior.

**Comment by malware-dev** [comment]
Ah. I didn't notice that. Your GetProperties implementation is incorrect. This is not how terminal properties work. There's no correlation between terminal properties and the data type of the block. Reflection cannot help you here.

Finally, while not a showstopper, please follow traditional C# coding standards. Even constants are PascalCased in C#.
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions#static-members

**Comment by kwilliams1987** [comment]
That last part about the `non-standard default values` is a typo, all the defaults I added were the ones a block gets by default when added in creative mode (as far as I could ascertain).

I will have a look for a better approach to mocking the Grid, entity IDs and ownership without using any statics.

The constants I will fix, it's a bad habit from working in PHP for many years.

**Comment by kwilliams1987** [comment]
For GetProperties() it will have to remain custom coded for every IMyTerminalBlock child then?
From what I was able to see using it, each property in the IMy* interface with a get and set accessor is available to the script via GetProperty(name), and by extension in the collection obtained via GetProperties().

This is why I took the Reflection route to obtain all the properties of the Mock object.

**Comment by malware-dev** [comment]
Yes, it must be explicitly implemented, because terminal properties are linked to the game's control panel controls, not the interface members.

**Comment by malware-dev** [comment]
Also you don't need to make any effort with the ownership. Like I said, that is irrelevant for the programmable block. You only have access to the blocks you... well, have access to :P

**Comment by malware-dev** [comment]
For the terminal properties and -actions, they're inherited. So MyTerminalBlock may define some of them, and MyFunctionalBlock defines some more, and then the final completely specific ones are defined in each block class.

**Comment by kwilliams1987** [comment]
I've started a method using base implementation of GetProperties() which requires the child classes to implement a Properties collection.

This way we can insure all the properties are correctly assigned.

I realize that implementing the Properties and Actions is actually less efficient than just accessing the properties or methods of the objects directly. :|

**Comment by malware-dev** [comment]
Of course they are, which is why they're effectively obsoleted as much of the data and methods they invoked have been implemented directly.

**Comment by kwilliams1987** [comment]
They are effectively obsolete... unless you want to save the current state of an arbitrary terminal block to restore later from custom data... like the script I'm working on does :(

**Comment by malware-dev** [comment]
No, not "unless", I'm afraid. Obsoletion happens from the provider's point of use, not users'. They're legacy. Their only real remaining use is for mod extensions as that's the only way to communicate with mod code. Don't get me wrong though. They should still be supported here in this project, if for no other reason that they're highly unlikely to be removed, so they will still be used... but _I_ will keep recommending to stay away from them in my teachings. The overhead isn't worth it.

**Review by malware-dev — CHANGES_REQUESTED** [review]
1. Find an alternative solution to the statics. Statics are bad, m'kay.

2. Implement proper terminal properties. They are not a simple reflection thing, every individual property is manually added to the block.

3. Use a traditional C# standard (not a showstopper).

**Comment by kwilliams1987** [comment]
1. For now I've simply removed the Mock Grid System helpers, I will make a project out of it.
2. Created a framework for this with the `protected abstract MockTerminalBlock.Properties` property.
  - Implemented for existing Mock Blocks.
3. The linting issues you highlighted are fixed. It's possible my IDE isn't 100% Microsoft compliant as it's setup for my companies golden rules.

**Comment by malware-dev** [comment]
Yeah no worries, I'm just trying to figure out how these GitHub review things works 😄 I need to get time to actually download and test your changes as it's getting a bit large, but I think this should be just fine.

**Pull request merged**
